#!/usr/bin/env bash
# QuadClaude delegation worker — GENERATED by QuadClaude (edits may be overwritten).
# Hands a one-shot coding task to the cheaper model you chose for delegation so it edits
# files and returns a tight summary. Two engines, selected by QC_ENGINE:
#   aider  (DEFAULT) — runs `aider --architect --auto-test` straight against the model's
#                      OpenAI-compatible endpoint. aider uses SEARCH/REPLACE diff edits
#                      (not Claude Code's tool-call protocol), which small models handle
#                      far more reliably, it discovers target files via its repo map, and
#                      with QC_CHECK it auto-runs the check and iterates toward green.
#   claude            — legacy path: real `claude -p` routed through claude-code-router
#                      (ccr) to the model. Kept as a fallback (and for non-git projects,
#                      where aider can't operate); auto-selected when not in a git repo.
#
# Either way this script stays QuadClaude's source of truth for delegation metrics: for
# every run it records ONE structured JSON line to ~/.quadclaude/events.jsonl capturing
# project + pane, route, duration, exit, how many lines/files actually changed (a git
# snapshot diff that never touches your index), and — if QC_CHECK is set — whether that
# check passed (objective ground truth). The app reads events.jsonl for the dashboard.
#
# Watch it live: tail -f ~/.quadclaude/delegation.log
set -o pipefail

qc="$HOME/.quadclaude"
log="$qc/delegation.log"
events="$qc/events.jsonl"
route_file="$qc/delegation-model"
mkdir -p "$qc"

# Feed targets. Everything still goes to the global delegation.log (the "All" feed), and
# ALSO to a per-orchestrator file ~/.quadclaude/feed/<QC_PANE>.log when we know which
# QuadClaude pane launched us — so a feed pane scoped to this Claude session sees only its
# own delegations. Empty QC_PANE (e.g. run outside QuadClaude) -> global feed only.
feeds=("$log")
if [ -n "$QC_PANE" ]; then mkdir -p "$qc/feed"; feeds+=("$qc/feed/$QC_PANE.log"); fi

route="$(cat "$route_file" 2>/dev/null | tr -d '[:space:]')"
if [ -z "$route" ]; then
  echo "qcdelegate: no delegation model set. Pick one in QuadClaude -> Settings -> Models." >&2
  exit 1
fi

engine="${QC_ENGINE:-aider}"

# aider needs a real git repo to work in. If we're not in one, fall back to the legacy
# claude/ccr engine, which carries its own shadow-git for non-git projects.
in_git=0
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then in_git=1; fi
if [ "$engine" = "aider" ] && [ "$in_git" -ne 1 ]; then
  printf '\033[2mqcdelegate: not a git repo — falling back to the claude engine for this run.\033[0m\n' | tee -a "${feeds[@]}"
  engine="claude"
fi

# --- Per-engine dependency checks ------------------------------------------
# If the default aider engine isn't installed, fall back to the legacy claude/ccr engine
# rather than failing — delegation keeps working, just without aider's nicer loop.
if [ "$engine" = "aider" ] && ! command -v aider >/dev/null 2>&1; then
  printf '\033[2mqcdelegate: aider not installed — falling back to the claude engine. Install aider for the better loop: python3 -m pip install --user aider-install && aider-install (or brew install aider).\033[0m\n' | tee -a "${feeds[@]}"
  engine="claude"
fi
if [ "$engine" = "aider" ]; then
  : # aider present and confirmed above
else
  if ! command -v ccr >/dev/null 2>&1; then
    echo "qcdelegate: claude-code-router not found. Install: npm i -g @musistudio/claude-code-router" >&2
    exit 127
  fi
  if ! command -v claude >/dev/null 2>&1; then
    echo "qcdelegate: the 'claude' CLI was not found on PATH." >&2
    exit 127
  fi
  # Ensure ccr's local router is up. Start it DETACHED only if the port is down —
  # a foreground ccr start would hang this worker.
  if ! curl -s -o /dev/null "http://127.0.0.1:3456" 2>/dev/null; then
    (ccr start >/dev/null 2>&1 &)
  fi
  for _ in $(seq 1 30); do curl -s -o /dev/null "http://127.0.0.1:3456" && break; sleep 0.3; done
fi

# --- Resolve the provider's real endpoint from ccr's config (single source of truth for
# the model route, used by both engines). Emits "base<TAB>key<TAB>model" for aider, and
# powers the preflight below. ----------------------------------------------
provmeta="$(CCR_CONFIG="$HOME/.claude-code-router/config.json" QC_ROUTE="$route" node -e '
try{
  const fs=require("fs");
  const cfg=JSON.parse(fs.readFileSync(process.env.CCR_CONFIG,"utf8"));
  const [slug,model]=(process.env.QC_ROUTE||"").split(",");
  const p=(cfg.Providers||[]).find(x=>x.name===slug);
  if(!p||!p.api_base_url){process.exit(0);}
  const base=p.api_base_url.replace(/\/chat\/completions\/?$/,"");
  process.stdout.write([base,(p.api_key||""),(model||(p.models||[])[0]||"")].join("\t"));
}catch(e){}
' 2>/dev/null)"
oai_base="${provmeta%%$'\t'*}"; _rest="${provmeta#*$'\t'}"; oai_key="${_rest%%$'\t'*}"; oai_model="${_rest##*$'\t'}"

# --- Preflight: is the endpoint serving the model, or bounced to a login page? When the
# LarePass VPN is OFF, the Olares host 303-redirects to its auth gateway and returns HTML;
# the worker otherwise churns minutes before dying on "Unexpected token '<'". Probe for a
# JSON 200 and fail fast. Set QC_NO_PREFLIGHT=1 to skip. Fails OPEN if it can't introspect.
if [ -z "$QC_NO_PREFLIGHT" ] && command -v node >/dev/null 2>&1; then
  pf="$(CCR_CONFIG="$HOME/.claude-code-router/config.json" QC_ROUTE="$route" node - <<'NODE' 2>/dev/null
const fs=require('fs');
(async()=>{
  try{
    const cfg=JSON.parse(fs.readFileSync(process.env.CCR_CONFIG,'utf8'));
    const [slug,model]=(process.env.QC_ROUTE||'').split(',');
    const p=(cfg.Providers||[]).find(x=>x.name===slug);
    if(!p||!p.api_base_url||typeof fetch!=='function'){console.log('SKIP');return;}
    const body=JSON.stringify({model:model||(p.models||[])[0],messages:[{role:'user',content:'ping'}],stream:false,max_tokens:1});
    const ctrl=new AbortController(); const t=setTimeout(()=>ctrl.abort(),20000);
    const r=await fetch(p.api_base_url,{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(p.api_key||'')},body,signal:ctrl.signal});
    clearTimeout(t);
    const ct=(r.headers.get('content-type')||''); const txt=(await r.text()).slice(0,40).trimStart();
    if(r.status>=200&&r.status<300&&ct.includes('json')) console.log('OK');
    else if((r.status>=300&&r.status<400)||ct.includes('html')||txt.startsWith('<')) console.log('AUTH');
    else console.log('ERR'+r.status);
  }catch(e){ console.log(String(e&&e.message||e).includes('abort')?'TIMEOUT':'SKIP'); }
})();
NODE
)"
  case "$pf" in
    OK|SKIP|'') : ;;  # serving JSON, or couldn't introspect — proceed
    AUTH) echo "qcdelegate: the inference endpoint redirected to an auth/login page (HTML) instead of serving the model. The LarePass VPN is most likely OFF (or the Olares session lapsed). Enable the VPN, run 'qcdoctor' to confirm the model is reachable, then retry. (skipped minutes of wasted work)" >&2; exit 4 ;;
    TIMEOUT) echo "qcdelegate: the inference endpoint timed out after 20s (VPN flaky, or model very cold). Retry; if it persists, check the Olares box." >&2; exit 4 ;;
    ERR*) echo "qcdelegate: the inference endpoint returned an unexpected status ($pf). Check the LarePass VPN and the Olares endpoint, then retry." >&2; exit 4 ;;
  esac
fi

printf '\n\033[38;5;173m-- %s . delegate via %s (%s) --------------------\033[0m\n\033[2m%s\033[0m\n' \
  "$(date '+%H:%M:%S')" "$engine" "$route" "$*" | tee -a "${feeds[@]}"

# Compose the worker prompt: prepend a per-task brief if the orchestrator left one in
# the working dir. Durable context belongs in CLAUDE.md (auto-loaded by the worker); the
# brief is for this-task-only context the worker can't infer from the code.
brief="$PWD/.quadclaude-brief.md"
if [ -f "$brief" ]; then
  prompt="$(printf '## Context from your orchestrator -- read this before acting\n%s\n\n## Your task\n%s' "$(cat "$brief")" "$*")"
else
  prompt="$*"
fi

# --- Attribution setup -----------------------------------------------------
# We measure exactly what the worker changes by diffing a worktree snapshot taken
# before vs. after, using a throwaway index so the user's real git staging is never
# touched. For non-git projects we keep a shadow repo under ~/.quadclaude/shadow so we
# never write anything into the project directory.
project="$PWD"
gitmode="none"
if [ "$in_git" -eq 1 ]; then
  project="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
  gitmode="repo"
else
  slug="$(printf %s "$project" | tr -c 'A-Za-z0-9' '_')"
  GIT_DIR="$qc/shadow/$slug.git"
  GIT_WORK_TREE="$project"
  export GIT_DIR GIT_WORK_TREE
  mkdir -p "$qc/shadow"
  git init -q "$GIT_DIR" >/dev/null 2>&1 || true
  gitmode="shadow"
fi

# Snapshot the current worktree to a tree object (respects .gitignore); echo its sha.
snap() {
  local idx sha
  # mktemp -u: a path that does NOT exist yet, so git creates a valid fresh index.
  # (An existing empty file is rejected as "index file smaller than expected".)
  idx="$(mktemp -u)"
  GIT_INDEX_FILE="$idx" git add -A >/dev/null 2>&1
  sha="$(GIT_INDEX_FILE="$idx" git write-tree 2>/dev/null)"
  rm -f "$idx"
  printf %s "$sha"
}
before_tree="$(snap)"

# --- Run the worker --------------------------------------------------------
t0=$SECONDS
pchars="$(printf %s "$prompt" | wc -c | tr -d ' ')"
out="$(mktemp)"
rc=0
cold=0

if [ "$engine" = "aider" ]; then
  # aider drives the model directly over its OpenAI-compatible endpoint (no ccr / no
  # tool-call transformer needed). --architect: a planning pass then an edit pass. With
  # QC_CHECK we let aider run it after each edit (--auto-test) and iterate toward green;
  # we still re-run QC_CHECK below for an independent ground-truth verdict.
  ahist="$(mktemp)"
  testargs=()
  if [ -n "$QC_CHECK" ]; then testargs=(--auto-test --test-cmd "$QC_CHECK"); fi
  OPENAI_API_BASE="$oai_base" OPENAI_API_KEY="${oai_key:-ollama}" \
    aider \
      --architect \
      --model "openai/${oai_model}" \
      --editor-model "openai/${oai_model}" \
      --yes-always \
      --no-auto-commits \
      --no-analytics \
      --no-check-update \
      --no-stream \
      --no-gitignore \
      --chat-history-file "$ahist" \
      --input-history-file /dev/null \
      --llm-history-file /dev/null \
      "${testargs[@]}" \
      --message "$prompt" >"$out" 2>&1
  rc=$?
  rm -f "$ahist"
else
  # Legacy engine: real Claude Code one-shot routed through ccr, with cold-start retry. A
  # freshly-loaded local model reports the route as "may not exist" until resident; the
  # failed attempt itself warms it, so we retry and count warm-ups (coldStartRetries).
  attempt=1
  while [ "$attempt" -le 3 ]; do
    : > "$out"
    printf %s "$prompt" | ANTHROPIC_BASE_URL="http://127.0.0.1:3456" \
      ANTHROPIC_AUTH_TOKEN="ccr" \
      ANTHROPIC_MODEL="$route" \
      claude -p --dangerously-skip-permissions \
        --allowedTools "Read Write Edit MultiEdit Bash Glob Grep LS TodoWrite" >"$out" 2>&1
    rc=$?
    if [ "$attempt" -lt 3 ] && grep -qiE "may not exist|may not have access|model.*not found" "$out"; then
      cold=$((cold + 1))
      printf '\033[2mqcdelegate: model cold -- warming and retrying (%s)...\033[0m\n' "$attempt" | tee -a "${feeds[@]}"
      sleep 2
      attempt=$((attempt + 1))
      continue
    fi
    break
  done
fi
cat "$out" | tee -a "${feeds[@]}"
dur=$((SECONDS - t0))

# --- Attribution: diff the after-snapshot against the before-snapshot ------
# Ignore aider's own scratch files (.aider*) so they never show up as "delegated" work.
after_tree="$(snap)"
ins=0
del=0
files=""
if [ -n "$before_tree" ] && [ -n "$after_tree" ] && [ "$before_tree" != "$after_tree" ]; then
  numstat="$(git diff --numstat "$before_tree" "$after_tree" 2>/dev/null | awk '$3 !~ /(^|\/)\.aider/')"
  ins="$(printf '%s\n' "$numstat" | awk '{s+=$1} END{print s+0}')"
  del="$(printf '%s\n' "$numstat" | awk '{s+=$2} END{print s+0}')"
  files="$(printf '%s\n' "$numstat" | awk 'NF{print $3}' | head -50 | paste -sd';' -)"
fi

# --- Ground-truth check: did the delegated change actually work? -----------
ckcmd="$QC_CHECK"
ckx="null"
if [ -n "$ckcmd" ]; then
  sh -c "$ckcmd" >/dev/null 2>&1
  ckx=$?
fi

# --- Emit one structured event (dependency-free; the app reads this) -------
# Skip telemetry for QC_NOLOG runs (e.g. connectivity warm-up pings) so they don't
# pollute delegation stats.
if [ -n "$QC_NOLOG" ]; then rm -f "$out"; exit "$rc"; fi
# Completion status line into the feed so the worker window shows a clear RESULT.
ckdisp="no check"; if [ -n "$ckcmd" ]; then [ "$ckx" = "0" ] && ckdisp="check ✓" || ckdisp="check ✗($ckx)"; fi
printf '\033[2m── done · %s · exit %s · %s · +%s/-%s lines · %ss ──\033[0m\n' "$engine" "$rc" "$ckdisp" "$ins" "$del" "$dur" | tee -a "${feeds[@]}"
# Escape a value for embedding inside a JSON string: backslash, quote, and any
# control chars (newline/CR/tab) flattened to spaces so the JSON stays valid.
jesc() { printf %s "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr '\n\r\t' '   '; }
ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
qtask="$QC_TASK"; [ -z "$qtask" ] && qtask="untagged"
qpane="$QC_PANE"
if [ -n "$ckcmd" ]; then
  check_json="{\"command\":\"$(jesc "$ckcmd")\",\"exit\":$ckx}"
else
  check_json="null"
fi
# Previews: what was delegated (first 1000 chars of the prompt) and how the worker
# responded (last 1500 chars of output) — the signal for analyzing delegation quality.
prompt_preview="$(printf %s "$prompt" | head -c 1000)"
output_preview="$(tail -c 1500 "$out" 2>/dev/null | sed -E 's/\x1b\[[0-9;]*m//g')"
# Persist the FULL prompt to a lazy per-call store so the dashboard can show it on demand
# without bloating events.jsonl (the preview stays inline; full text loads only when clicked).
# Named deterministically by ts+task so the app finds it from the event.
pkey="$(printf %s "${ts}_${qtask}" | tr -c 'A-Za-z0-9._-' '_')"
mkdir -p "$qc/prompts"
printf %s "$prompt" > "$qc/prompts/$pkey.txt" 2>/dev/null || true
printf '{"ts":"%s","type":"delegation","engine":"%s","project":"%s","pane":"%s","task":"%s","route":"%s","durationSec":%s,"exit":%s,"promptChars":%s,"coldStartRetries":%s,"gitMode":"%s","insertions":%s,"deletions":%s,"files":"%s","check":%s,"promptPreview":"%s","outputPreview":"%s"}\n' \
  "$ts" "$(jesc "$engine")" "$(jesc "$project")" "$(jesc "$qpane")" "$(jesc "$qtask")" "$(jesc "$route")" \
  "$dur" "$rc" "$pchars" "$cold" "$gitmode" "$ins" "$del" "$(jesc "$files")" "$check_json" \
  "$(jesc "$prompt_preview")" "$(jesc "$output_preview")" >> "$events"

# Continuously-learning evaluator: append a labeled outcome to the durable eval memory
# (~/.quadclaude/eval — lives in $HOME, survives app updates, never cleared by the
# dashboard). Over projects this teaches the keep/delegate decision which work qwen
# handles reliably. Best-effort; never blocks or fails the worker.
if command -v qceval >/dev/null 2>&1; then
  QCE_PROJECT="$project" QCE_TASK="$qtask" QCE_ENGINE="$engine" QCE_ROUTE="$route" \
    QCE_FILES="$files" QCE_INS="$ins" QCE_DEL="$del" QCE_PROMPTCHARS="$pchars" \
    QCE_CHECK_EXIT="$([ -n "$ckcmd" ] && printf %s "$ckx")" QCE_SOURCE="qcdelegate" \
    qceval record >/dev/null 2>&1 || true
fi

# Adversarial verifier: run the multi-judge panel over the worker's diff when asked
# (QC_JUDGE=1) OR whenever there's no runnable QC_CHECK — in that case the panel is the
# ONLY verification, so a green-looking result isn't trusted blind. Skippable with
# QC_NO_JUDGE=1. Best-effort; never blocks. Votes fold back into the eval memory.
if command -v qceval >/dev/null 2>&1 && [ -z "$QC_NO_JUDGE" ] && { [ -n "$QC_JUDGE" ] || [ -z "$ckcmd" ]; }; then
  QC_TASK="$qtask" qceval judge "$*" 2>&1 | tee -a "${feeds[@]}" || true
fi

# Backward-compat: keep feeding a user-installed qctrace tool if present.
if command -v qctrace >/dev/null 2>&1; then
  pf="$(mktemp)"; printf %s "$prompt" > "$pf"
  QC_PROMPT_FILE="$pf" QC_FILES="$files" QC_CHECK_CMD="$ckcmd" QC_CHECK_EXIT="$ckx" \
    qctrace delegate "$qtask" "$route" "$dur" "$rc" "$pchars" || true
  rm -f "$pf"
fi

rm -f "$out"
exit "$rc"
