#!/usr/bin/env bash
# QuadClaude delegation worker — GENERATED by QuadClaude (edits may be overwritten).
# Runs a one-shot Claude Code session routed through claude-code-router to the model
# you chose for delegation, so a cheaper model edits files and returns a tight summary.
#
# Beyond running the worker, this script is QuadClaude's source of truth for delegation
# metrics. For every run it records ONE structured JSON line to ~/.quadclaude/events.jsonl
# capturing: which project + pane it ran in, the route, duration, exit code, how many
# lines/files the worker actually changed (measured by a git snapshot diff that never
# touches your index), and — if QC_CHECK is set — whether that check passed (objective
# ground truth for "did delegation work?"). The app reads events.jsonl to answer
# "how much of this project was delegated, and did it work?".
#
# Watch it live: tail -f ~/.quadclaude/delegation.log
set -o pipefail

qc="$HOME/.quadclaude"
log="$qc/delegation.log"
events="$qc/events.jsonl"
route_file="$qc/delegation-model"
mkdir -p "$qc"

route="$(cat "$route_file" 2>/dev/null | tr -d '[:space:]')"
if [ -z "$route" ]; then
  echo "qcdelegate: no delegation model set. Pick one in QuadClaude -> Settings -> Models." >&2
  exit 1
fi
if ! command -v ccr >/dev/null 2>&1; then
  echo "qcdelegate: claude-code-router not found. Install: npm i -g @musistudio/claude-code-router" >&2
  exit 127
fi
if ! command -v claude >/dev/null 2>&1; then
  echo "qcdelegate: the 'claude' CLI was not found on PATH." >&2
  exit 127
fi

# Ensure ccr's local router is up. Start it DETACHED only if the port is down —
# a foreground ccr start would hang this worker.
if ! curl -s -o /dev/null "http://127.0.0.1:3456" 2>/dev/null; then
  (ccr start >/dev/null 2>&1 &)
fi
for _ in $(seq 1 30); do curl -s -o /dev/null "http://127.0.0.1:3456" && break; sleep 0.3; done

printf '\n\033[38;5;173m-- %s . delegate (%s) --------------------\033[0m\n\033[2m%s\033[0m\n' \
  "$(date '+%H:%M:%S')" "$route" "$*" | tee -a "$log"

# Compose the worker prompt: prepend a per-task brief if the orchestrator left one in
# the working dir. Durable context belongs in CLAUDE.md (auto-loaded by the worker); the
# brief is for this-task-only context the worker can't infer from the code.
brief="$PWD/.quadclaude-brief.md"
if [ -f "$brief" ]; then
  prompt="$(printf '## Context from your orchestrator -- read this before acting\n%s\n\n## Your task\n%s' "$(cat "$brief")" "$*")"
else
  prompt="$*"
fi

# --- Attribution setup -----------------------------------------------------
# We measure exactly what the worker changes by diffing a worktree snapshot taken
# before vs. after, using a throwaway index so the user's real git staging is never
# touched. For non-git projects we keep a shadow repo under ~/.quadclaude/shadow so we
# never write anything into the project directory.
project="$PWD"
gitmode="none"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  project="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
  gitmode="repo"
else
  slug="$(printf %s "$project" | tr -c 'A-Za-z0-9' '_')"
  GIT_DIR="$qc/shadow/$slug.git"
  GIT_WORK_TREE="$project"
  export GIT_DIR GIT_WORK_TREE
  mkdir -p "$qc/shadow"
  git init -q "$GIT_DIR" >/dev/null 2>&1 || true
  gitmode="shadow"
fi

# Snapshot the current worktree to a tree object (respects .gitignore); echo its sha.
snap() {
  local idx sha
  # mktemp -u: a path that does NOT exist yet, so git creates a valid fresh index.
  # (An existing empty file is rejected as "index file smaller than expected".)
  idx="$(mktemp -u)"
  GIT_INDEX_FILE="$idx" git add -A >/dev/null 2>&1
  sha="$(GIT_INDEX_FILE="$idx" git write-tree 2>/dev/null)"
  rm -f "$idx"
  printf %s "$sha"
}
before_tree="$(snap)"

# --- Run the worker, with cold-start retry ---------------------------------
# A freshly-loaded local model (e.g. Ollama) reports the route as "may not exist"
# until it is resident in memory; the failed attempt itself warms it, so we retry a
# couple of times and count how many warm-ups it took (coldStartRetries in telemetry).
t0=$SECONDS
pchars="$(printf %s "$prompt" | wc -c | tr -d ' ')"
out="$(mktemp)"
rc=0
cold=0
attempt=1
while [ "$attempt" -le 3 ]; do
  : > "$out"
  printf %s "$prompt" | ANTHROPIC_BASE_URL="http://127.0.0.1:3456" \
    ANTHROPIC_AUTH_TOKEN="ccr" \
    ANTHROPIC_MODEL="$route" \
    claude -p --dangerously-skip-permissions \
      --allowedTools "Read Write Edit MultiEdit Bash Glob Grep LS TodoWrite" >"$out" 2>&1
  rc=$?
  if [ "$attempt" -lt 3 ] && grep -qiE "may not exist|may not have access|model.*not found" "$out"; then
    cold=$((cold + 1))
    printf '\033[2mqcdelegate: model cold -- warming and retrying (%s)...\033[0m\n' "$attempt" | tee -a "$log"
    sleep 2
    attempt=$((attempt + 1))
    continue
  fi
  break
done
cat "$out" | tee -a "$log"
dur=$((SECONDS - t0))

# --- Attribution: diff the after-snapshot against the before-snapshot ------
after_tree="$(snap)"
ins=0
del=0
files=""
if [ -n "$before_tree" ] && [ -n "$after_tree" ] && [ "$before_tree" != "$after_tree" ]; then
  numstat="$(git diff --numstat "$before_tree" "$after_tree" 2>/dev/null)"
  ins="$(printf '%s\n' "$numstat" | awk '{s+=$1} END{print s+0}')"
  del="$(printf '%s\n' "$numstat" | awk '{s+=$2} END{print s+0}')"
  files="$(printf '%s\n' "$numstat" | awk 'NF{print $3}' | head -50 | paste -sd';' -)"
fi

# --- Ground-truth check: did the delegated change actually work? -----------
ckcmd="$QC_CHECK"
ckx="null"
if [ -n "$ckcmd" ]; then
  sh -c "$ckcmd" >/dev/null 2>&1
  ckx=$?
fi

# --- Emit one structured event (dependency-free; the app reads this) -------
# Skip telemetry for QC_NOLOG runs (e.g. connectivity warm-up pings) so they don't
# pollute delegation stats.
if [ -n "$QC_NOLOG" ]; then rm -f "$out"; exit "$rc"; fi
# Escape a value for embedding inside a JSON string: backslash, quote, and any
# control chars (newline/CR/tab) flattened to spaces so the JSON stays valid.
jesc() { printf %s "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr '\n\r\t' '   '; }
ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
qtask="$QC_TASK"; [ -z "$qtask" ] && qtask="untagged"
qpane="$QC_PANE"
if [ -n "$ckcmd" ]; then
  check_json="{\"command\":\"$(jesc "$ckcmd")\",\"exit\":$ckx}"
else
  check_json="null"
fi
# Previews: what was delegated (first 1000 chars of the prompt) and how the worker
# responded (last 1500 chars of output) — the signal for analyzing delegation quality.
prompt_preview="$(printf %s "$prompt" | head -c 1000)"
output_preview="$(tail -c 1500 "$out" 2>/dev/null | sed -E 's/\x1b\[[0-9;]*m//g')"
printf '{"ts":"%s","type":"delegation","project":"%s","pane":"%s","task":"%s","route":"%s","durationSec":%s,"exit":%s,"promptChars":%s,"coldStartRetries":%s,"gitMode":"%s","insertions":%s,"deletions":%s,"files":"%s","check":%s,"promptPreview":"%s","outputPreview":"%s"}\n' \
  "$ts" "$(jesc "$project")" "$(jesc "$qpane")" "$(jesc "$qtask")" "$(jesc "$route")" \
  "$dur" "$rc" "$pchars" "$cold" "$gitmode" "$ins" "$del" "$(jesc "$files")" "$check_json" \
  "$(jesc "$prompt_preview")" "$(jesc "$output_preview")" >> "$events"

# Backward-compat: keep feeding a user-installed qctrace tool if present.
if command -v qctrace >/dev/null 2>&1; then
  pf="$(mktemp)"; printf %s "$prompt" > "$pf"
  QC_PROMPT_FILE="$pf" QC_FILES="$files" QC_CHECK_CMD="$ckcmd" QC_CHECK_EXIT="$ckx" \
    qctrace delegate "$qtask" "$route" "$dur" "$rc" "$pchars" || true
  rm -f "$pf"
fi

rm -f "$out"
exit "$rc"
