#!/usr/bin/env bash
# qcdecide — GENERATED by QuadClaude. Record an orchestrator KEEP/DELEGATE decision for
# one unit of work ("group"), so the decision AND its reason are visible everywhere:
#   • printed in the orchestrator pane (this command's stdout),
#   • echoed into the worker feed (~/.quadclaude/delegation.log, which the worker pane tails),
#   • logged for the delegation dashboard (~/.quadclaude/events.jsonl, type:"decision").
#
# Usage:
#   qcdecide "<group>" keep|delegate "<reason>" ["<check-command>"]
# Examples:
#   qcdecide "combat system" keep "determinism-critical core math"
#   qcdecide "monster data" delegate "spec-driven JSON" "node test/validate_monsters.mjs"
set -o pipefail
qc="$HOME/.quadclaude"; log="$qc/delegation.log"; events="$qc/events.jsonl"; mkdir -p "$qc"

group="$1"; verdict="$2"; reason="$3"; check="$4"
if [ -z "$group" ] || { [ "$verdict" != "keep" ] && [ "$verdict" != "delegate" ]; }; then
  echo 'usage: qcdecide "<group>" keep|delegate "<reason>" ["<check-cmd>"]' >&2
  exit 2
fi

project="$PWD"
if git rev-parse --show-toplevel >/dev/null 2>&1; then project="$(git rev-parse --show-toplevel)"; fi
ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# KEEP = blue (39); DELEGATE = orange (173) — matches the delegation feed accent.
if [ "$verdict" = "delegate" ]; then col=173; label="DELEGATE → qwen"; else col=39; label="KEEP (Claude)"; fi
extra=""; [ "$verdict" = "delegate" ] && [ -n "$check" ] && extra="  · check: $check"
printf '\n\033[38;5;%sm── %s · decision · %s → %s ──\033[0m\n\033[2m%s%s\033[0m\n' \
  "$col" "$(date '+%H:%M:%S')" "$group" "$label" "$reason" "$extra" | tee -a "$log"

jesc() { printf %s "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr '\n\r\t' '   '; }
printf '{"ts":"%s","type":"decision","project":"%s","pane":"%s","group":"%s","verdict":"%s","reason":"%s","check":"%s"}\n' \
  "$ts" "$(jesc "$project")" "$(jesc "$QC_PANE")" "$(jesc "$group")" "$verdict" "$(jesc "$reason")" "$(jesc "$check")" >> "$events"
