#!/usr/bin/env bash
# qcdoctor — GENERATED by QuadClaude. One-shot, real-time health check of the WHOLE
# delegation pipeline, so you can see at a glance whether delegation will work and, if
# not, exactly which link is broken. Run it anytime: `qcdoctor`.
qc="$HOME/.quadclaude"
g='\033[32m'; r='\033[31m'; y='\033[33m'; d='\033[2m'; n='\033[0m'
ok(){ printf "  ${g}✓${n} %s\n" "$1"; }
bad(){ printf "  ${r}✗${n} %s\n" "$1"; }
warn(){ printf "  ${y}!${n} %s\n" "$1"; }

printf "\n${d}── qcdoctor · delegation pipeline health ──${n}\n\n"

# 1. Toggle (authoritative status the app publishes)
active="$(cat "$qc/delegation-active" 2>/dev/null)"
if [ -n "$active" ] && [ "$active" != "off" ]; then ok "delegation toggle: ON → $active"
else bad "delegation toggle: OFF (enable it in QuadClaude → Delegation). delegation-active='${active:-<missing>}'"; fi

# 2. Model route configured
route="$(cat "$qc/delegation-model" 2>/dev/null)"
[ -n "$route" ] && ok "delegation model: $route" || bad "no delegation model set (Settings → Models → Delegate with)"

# 3. This session sees the toggle (env injected by the app at PTY create)
if [ -n "$QC_DELEGATION" ]; then ok "this pane's env: QC_DELEGATION=$QC_DELEGATION model=${QC_DELEGATION_MODEL:-?}"
else warn "QC_DELEGATION not in this shell's env (older pane, or launched outside QuadClaude) — orchestrator should read $qc/delegation-active instead"; fi

# 4. SessionStart hook present (auto-tells a new Claude session)
if grep -q "session-delegation-hook" "$HOME/.claude/settings.json" 2>/dev/null; then ok "SessionStart hook installed (new sessions auto-detect delegation)"
else warn "SessionStart hook not found in ~/.claude/settings.json"; fi

# 5. Tools on PATH
for c in qcdelegate qcdecide qwen; do
  command -v "$c" >/dev/null 2>&1 && ok "tool on PATH: $c" || bad "tool MISSING on PATH: $c"
done

# 5a. Durable learning memory (survives app updates; never cleared by the dashboard)
if command -v qceval >/dev/null 2>&1 && command -v qclearn >/dev/null 2>&1; then
  oc="$qc/eval/outcomes.jsonl"
  ocount="$( [ -f "$oc" ] && grep -c . "$oc" 2>/dev/null || echo 0 )"
  ok "eval memory: $ocount outcome(s) in ~/.quadclaude/eval (durable; qceval/qclearn on PATH)"
else warn "learning evaluator (qceval/qclearn) not on PATH — delegation won't self-improve"; fi

# 5b. Delegation engine: aider is the default worker (QC_ENGINE=aider). ccr/claude is the
# legacy fallback (QC_ENGINE=claude, also auto-used for non-git projects).
eng="${QC_ENGINE:-aider}"
if [ "$eng" = "aider" ]; then
  if command -v aider >/dev/null 2>&1; then ok "delegation engine: aider ($(aider --version 2>/dev/null | head -1))"
  else bad "delegation engine is aider but aider is MISSING — install: python3 -m pip install --user aider-install && aider-install (or brew install aider). Until then qcdelegate falls back to the claude engine."; fi
else
  ok "delegation engine: claude (legacy ccr path) via QC_ENGINE=claude"
fi

# 6. ccr inference router reachable
if curl -s -o /dev/null --max-time 3 "http://127.0.0.1:3456" 2>/dev/null; then ok "ccr router reachable (127.0.0.1:3456)"
else bad "ccr router NOT reachable on :3456 (qcdelegate auto-starts it; if it persists, check VPN/Olares)"; fi

# 6b. Persistent keeper (launchd agent that health-checks & restarts ccr every 60s)
plist="$HOME/Library/LaunchAgents/com.quadclaude.ccr.plist"
if launchctl list 2>/dev/null | grep -q "com.quadclaude.ccr"; then ok "ccr keeper: persistent (launchd com.quadclaude.ccr loaded — auto-restarts ccr)"
elif [ -f "$plist" ]; then warn "ccr keeper installed but NOT loaded — run: launchctl load -w \"$plist\""
else warn "ccr keeper NOT installed — ccr only starts on first delegation and dies with the shell; install com.quadclaude.ccr for persistence"; fi

# 7. Recent activity (decisions + delegations) — the real-time trace
printf "\n${d}── recent activity (last 8) ──${n}\n"
if [ -s "$qc/events.jsonl" ]; then
  tail -8 "$qc/events.jsonl" | node -e '
    let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{
      for(const l of d.split("\n")){const t=l.trim();if(!t)continue;try{const e=JSON.parse(t);
        const ts=(e.ts||"").slice(11,19);
        if(e.type==="decision") console.log(`  ${ts}  decision  ${e.verdict.toUpperCase().padEnd(8)} ${e.group} — ${e.reason}`);
        else if(e.type==="delegation"){const ck=e.check?(e.check.exit===0?"check✓":"check✗"):"no-check"; console.log(`  ${ts}  delegate  exit${e.exit} ${ck} +${e.insertions} [${e.task}] ${(e.files||"").split(";").filter(Boolean).slice(0,3).join(",")}`);}
      }catch{}}
    })'
else printf "  ${d}(no delegation activity recorded yet)${n}\n"; fi

# 8. Worker window paired? (read the app workspace)
ws="$HOME/Library/Application Support/QuadClaude/workspace.json"
if [ -f "$ws" ]; then
  paired="$(node -e 'try{const w=require(process.argv[1]);const p=(w.workspace?.panes||[]).filter(x=>x.pairId);process.stdout.write(p.map(x=>x.label+":"+x.pairRole).join(", "))}catch{}' "$ws" 2>/dev/null)"
  printf "\n"; [ -n "$paired" ] && ok "worker window paired: $paired" || warn "no worker window paired yet (opens on first delegation when you approve the prompt; live feed = tail -F $qc/delegation.log)"
fi
printf "\n${d}watch the live feed:${n} tail -f %s/delegation.log\n\n" "$qc"
