// RouterManager — bridges QuadClaude to claude-code-router (ccr) so a pane can run
// the REAL `claude` TUI against any non-Anthropic model. QuadClaude never speaks an
// LLM API itself: it only writes ccr's local config file. ccr (launched as `ccr code`
// inside the pane's own shell) translates Anthropic's Messages API to/from the user's
// hosted provider, so the pane looks and behaves 100% like Claude Code.
//
// Config lives at ~/.claude-code-router/config.json (ccr's documented location).
import os from 'os'
import fs from 'fs'
import path from 'path'
import { execFile } from 'child_process'
import { logger } from './logger'
import { RouterProviderInput, RouterStatus, RouterSaveResult, RouterTestResult, RouterDelegationStatus } from '../shared/types'
import { MERGE_PLUGIN_B64 } from './ccr-plugins/merge-system.b64'

const CONFIG_DIR = path.join(os.homedir(), '.claude-code-router')
const CONFIG_PATH = path.join(CONFIG_DIR, 'config.json')

// The pane command. `ccr code` starts ccr's local router daemon if it isn't already
// up, then launches the genuine `claude` CLI pointed at it — no QuadClaude-managed
// daemon, so PATH/node resolution happens in the user's real login shell.
export const ROUTER_COMMAND = 'ccr code'

// --- Delegation -------------------------------------------------------------
// "Delegation" lets an orchestrator (your main Claude, in a pane) hand bulk work to a
// cheaper model via a one-shot shell command. We generate a generic `qcdelegate`
// worker that runs the real `claude -p` through ccr against whichever configured model
// the user picked — the model route lives in a plain file so switching models never
// rewrites the script. This is the productized, bring-your-own version of a personal
// delegate wrapper: nothing provider-specific is baked in.
const QC_DIR = path.join(os.homedir(), '.quadclaude')
const DELEGATION_ROUTE_FILE = path.join(QC_DIR, 'delegation-model')
const DELEGATION_LOG = path.join(QC_DIR, 'delegation.log')
const DELEGATE_BIN_DIR = path.join(os.homedir(), '.local', 'bin')
const DELEGATE_SCRIPT = path.join(DELEGATE_BIN_DIR, 'qcdelegate')

// Compatibility transformer: makes small/local models (e.g. qwen3-coder via Ollama)
// reliably tool-call under Claude Code's large prompt. We install it and route
// delegation through a dedicated "<slug>-delegate" provider that carries it, so the
// model's interactive panes keep full streaming + all tools.
const PLUGIN_DIR = path.join(CONFIG_DIR, 'plugins')
const MERGE_PLUGIN_PATH = path.join(PLUGIN_DIR, 'merge-system.js')
const COMPAT_TRANSFORMER = 'mergesystem'
const DELEGATE_PROVIDER_SUFFIX = '-delegate'
export const DELEGATE_COMMAND = 'qcdelegate'
export const DELEGATION_FEED_COMMAND =
  "sh -lc 'mkdir -p ~/.quadclaude && touch ~/.quadclaude/delegation.log && tail -F ~/.quadclaude/delegation.log'"

// The generated worker. Reads its target model from ~/.quadclaude/delegation-model so
// the user can repoint delegation without regenerating the script. Skips permission
// prompts so the worker can actually edit files (that's the whole point).
const DELEGATE_SCRIPT_BODY = `#!/usr/bin/env bash
# QuadClaude delegation worker — GENERATED by QuadClaude (edits may be overwritten).
# Runs a one-shot Claude Code session routed through claude-code-router to the model
# you chose for delegation, so a cheaper model edits files and returns a tight summary.
# Watch it live: tail -f ~/.quadclaude/delegation.log
set -o pipefail
log="$HOME/.quadclaude/delegation.log"
route_file="$HOME/.quadclaude/delegation-model"
mkdir -p "$(dirname "$log")"
route="$(cat "$route_file" 2>/dev/null | tr -d '[:space:]')"
if [ -z "$route" ]; then
  echo "qcdelegate: no delegation model set. Pick one in QuadClaude → Settings → Models." >&2
  exit 1
fi
if ! command -v ccr >/dev/null 2>&1; then
  echo "qcdelegate: claude-code-router not found. Install: npm i -g @musistudio/claude-code-router" >&2
  exit 127
fi
if ! command -v claude >/dev/null 2>&1; then
  echo "qcdelegate: the 'claude' CLI was not found on PATH." >&2
  exit 127
fi
# Ensure ccr's local router is up. Start it DETACHED only if the port is down —
# a foreground ccr start would hang this worker.
if ! curl -s -o /dev/null "http://127.0.0.1:3456" 2>/dev/null; then
  (ccr start >/dev/null 2>&1 &)
fi
for _ in $(seq 1 30); do curl -s -o /dev/null "http://127.0.0.1:3456" && break; sleep 0.3; done
printf '\\n\\033[38;5;173m── %s · delegate (%s) ─────────────────────\\033[0m\\n\\033[2m%s\\033[0m\\n' \\
  "$(date '+%H:%M:%S')" "$route" "$*" | tee -a "$log"
# Compose the worker prompt: prepend a per-task brief if the orchestrator left one in
# the working dir. Durable context belongs in CLAUDE.md (auto-loaded by the worker); the
# brief is for this-task-only context the worker can't infer from the code.
brief="$PWD/.quadclaude-brief.md"
if [ -f "$brief" ]; then
  prompt="$(printf '## Context from your orchestrator — read this before acting\\n%s\\n\\n## Your task\\n%s' "$(cat "$brief")" "$*")"
else
  prompt="$*"
fi
t0=$SECONDS
pchars=$(printf %s "$prompt" | wc -c | tr -d ' ')
printf %s "$prompt" | ANTHROPIC_BASE_URL="http://127.0.0.1:3456" \\
ANTHROPIC_AUTH_TOKEN="ccr" \\
ANTHROPIC_MODEL="$route" \\
  claude -p --dangerously-skip-permissions --allowedTools "Read Write Edit MultiEdit Bash Glob Grep LS TodoWrite" 2>&1 | tee -a "$log"
rc=$?
dur=$((SECONDS - t0))
qtask="$QC_TASK"; [ -z "$qtask" ] && qtask=untagged
# Rich telemetry: capture the exact prompt, the worker's diff, and (if QC_CHECK is set)
# a ground-truth check (tests/lint/build), then log it. No-op if qctrace is absent.
if command -v qctrace >/dev/null 2>&1; then
  pf=$(mktemp); printf %s "$prompt" > "$pf"
  df=$(mktemp); files=""
  if git rev-parse --git-dir >/dev/null 2>&1; then git diff > "$df" 2>/dev/null; files=$(git status --porcelain 2>/dev/null | head -40 | tr '\\n' ';'); fi
  ckx=""
  if [ -n "$QC_CHECK" ]; then sh -c "$QC_CHECK" >/dev/null 2>&1; ckx=$?; fi
  QC_PROMPT_FILE="$pf" QC_DIFF_FILE="$df" QC_FILES="$files" QC_CHECK_CMD="$QC_CHECK" QC_CHECK_EXIT="$ckx" \\
    qctrace delegate "$qtask" "$route" "$dur" "$rc" "$pchars" || true
  rm -f "$pf" "$df"
fi
`

// Minimal shape of ccr's config we touch. We preserve any other keys the user set.
interface CcrProvider {
  name: string
  api_base_url: string
  api_key: string
  models: string[]
  transformer?: Record<string, unknown>
}
interface CcrConfig {
  LOG?: boolean
  Providers?: CcrProvider[]
  Router?: Record<string, string>
  transformers?: Array<{ path: string; options?: Record<string, unknown> }>
  [key: string]: unknown
}

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '')
      .slice(0, 40) || 'model'
  )
}

export class RouterManager {
  private readConfig(): CcrConfig {
    try {
      if (!fs.existsSync(CONFIG_PATH)) return {}
      const raw = fs.readFileSync(CONFIG_PATH, 'utf8')
      const parsed = JSON.parse(raw)
      return parsed && typeof parsed === 'object' ? (parsed as CcrConfig) : {}
    } catch (error) {
      logger.error('router', 'Failed to read ccr config', error instanceof Error ? error.message : String(error))
      return {}
    }
  }

  private writeConfig(cfg: CcrConfig): void {
    fs.mkdirSync(CONFIG_DIR, { recursive: true })
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(cfg, null, 2), { encoding: 'utf8', mode: 0o600 })
  }

  // Is a command resolvable from the user's real login shell? We check via a login
  // shell (not main's process.env) so nvm/global-npm/~/.local PATHs are honored.
  private commandOnPath(cmd: string): Promise<boolean> {
    return new Promise((resolve) => {
      const shell = process.env.SHELL || (process.platform === 'win32' ? 'powershell.exe' : '/bin/zsh')
      const args = process.platform === 'win32' ? ['-Command', `Get-Command ${cmd}`] : ['-lc', `command -v ${cmd}`]
      execFile(shell, args, { timeout: 4000 }, (err, stdout) => {
        resolve(!err && !!String(stdout).trim())
      })
    })
  }

  detectCcr(): Promise<boolean> {
    return this.commandOnPath('ccr')
  }

  async status(): Promise<RouterStatus> {
    const cfg = this.readConfig()
    const ccrInstalled = await this.detectCcr()
    const providers = (cfg.Providers ?? []).map((p) => ({
      name: p.name,
      model: p.models?.[0] ?? '',
      baseUrl: p.api_base_url,
    }))
    return {
      configPath: CONFIG_PATH,
      ccrInstalled,
      installHint: 'npm install -g @musistudio/claude-code-router',
      command: ROUTER_COMMAND,
      providers,
    }
  }

  // Merge one provider into ccr's config and return the env + command a pane needs.
  // Idempotent per provider `name` (re-saving the same model updates it in place).
  async saveProvider(input: RouterProviderInput): Promise<RouterSaveResult> {
    try {
      const name = slugify(input.label || input.model)
      const model = input.model.trim()
      if (!input.baseUrl.trim() || !model) {
        return { ok: false, route: '', command: ROUTER_COMMAND, env: {}, ccrInstalled: false, error: 'Base URL and model are required.' }
      }

      const provider: CcrProvider = {
        name,
        api_base_url: input.baseUrl.trim(),
        api_key: input.apiKey ?? '',
        models: [model],
        ...(input.transformer ? { transformer: { use: [input.transformer] } } : {}),
      }

      const cfg = this.readConfig()
      const providers = (cfg.Providers ?? []).filter((p) => p.name !== name)
      providers.push(provider)
      cfg.Providers = providers

      const route = `${name},${model}`
      // Route Claude Code's requests to this model. `default` is the fallback the
      // single-model case always hits; per-pane selection rides on ANTHROPIC_MODEL.
      cfg.Router = { ...(cfg.Router ?? {}), default: route }
      // Quieter logs by default; users can flip this in the file.
      if (cfg.LOG === undefined) cfg.LOG = false

      this.writeConfig(cfg)
      logger.info('router', 'Saved ccr provider', `${name} -> ${model}`)

      const ccrInstalled = await this.detectCcr()
      return {
        ok: true,
        route,
        command: ROUTER_COMMAND,
        // ANTHROPIC_MODEL lets different panes target different providers concurrently:
        // ccr routes a "name,model"-formatted model directly to that provider entry.
        env: { ANTHROPIC_MODEL: route },
        ccrInstalled,
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error)
      logger.error('router', 'Failed to save provider', msg)
      return { ok: false, route: '', command: ROUTER_COMMAND, env: {}, ccrInstalled: false, error: msg }
    }
  }

  deleteProvider(name: string): void {
    const cfg = this.readConfig()
    if (!cfg.Providers) return
    cfg.Providers = cfg.Providers.filter((p) => p.name !== name)
    this.writeConfig(cfg)
    logger.info('router', 'Deleted ccr provider', name)
  }

  // Direct, lightweight reachability check: one tiny chat completion straight to the
  // provider (NOT through ccr), so the wizard can confirm the URL+key+model before a
  // pane is ever launched. Uses global fetch (Node 18+/Electron).
  async testConnection(input: RouterProviderInput): Promise<RouterTestResult> {
    const url = input.baseUrl.trim()
    if (!url) return { ok: false, error: 'Base URL is required.' }
    let host = ''
    try {
      host = new URL(url).host
    } catch {
      return { ok: false, error: 'Base URL is not a valid URL.' }
    }
    try {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), 15000)
      const res = await fetch(url, {
        method: 'POST',
        redirect: 'manual', // don't silently follow into a login page
        signal: controller.signal,
        headers: {
          'Content-Type': 'application/json',
          ...(input.apiKey ? { Authorization: `Bearer ${input.apiKey}` } : {}),
        },
        body: JSON.stringify({
          model: input.model,
          max_tokens: 8,
          messages: [{ role: 'user', content: 'ping' }],
        }),
      }).finally(() => clearTimeout(timer))

      // A redirect — especially to another host — is almost always an auth/SSO gateway.
      if (res.status >= 300 && res.status < 400) {
        const loc = res.headers.get('location') || ''
        let locHost = ''
        try {
          locHost = loc ? new URL(loc, url).host : ''
        } catch {
          /* unparseable location */
        }
        const where = locHost && locHost !== host ? ` to ${locHost}` : ''
        return {
          ok: false,
          error: `Endpoint redirected${where} — it's behind a login/SSO gateway. Check the URL, your API key, or your VPN session.`,
        }
      }

      const ctype = res.headers.get('content-type') || ''
      if (res.ok && ctype.includes('json')) return { ok: true }

      let detail = ''
      try {
        detail = (await res.text()).slice(0, 300)
      } catch {
        /* ignore body read errors */
      }
      // An HTML body means a web page, not an API.
      if (ctype.includes('html') || detail.trimStart().startsWith('<')) {
        return {
          ok: false,
          error:
            'Endpoint returned a web page, not JSON — it may be behind a login/SSO gateway, or the URL is wrong (it should be the /v1/chat/completions endpoint).',
        }
      }
      if (res.ok) return { ok: true }
      return { ok: false, error: `HTTP ${res.status}${detail ? `: ${detail}` : ''}` }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error)
      return { ok: false, error: msg.includes('abort') ? 'Request timed out.' : msg }
    }
  }

  // --- Delegation ------------------------------------------------------------

  private writeDelegateScript(): void {
    fs.mkdirSync(DELEGATE_BIN_DIR, { recursive: true })
    fs.writeFileSync(DELEGATE_SCRIPT, DELEGATE_SCRIPT_BODY, { encoding: 'utf8', mode: 0o755 })
  }

  // Install the compatibility transformer plugin and route delegation through a
  // dedicated "<slug>-delegate" provider that carries it. Returns the effective
  // route the worker should use (e.g. "olares-delegate,qwen3-coder:30b").
  private ensureDelegateProvider(route: string): string {
    const [slug, model] = route.split(',')
    if (!slug || !model) return route
    fs.mkdirSync(PLUGIN_DIR, { recursive: true })
    fs.writeFileSync(MERGE_PLUGIN_PATH, Buffer.from(MERGE_PLUGIN_B64, 'base64'))

    const cfg = this.readConfig()
    const transformers = cfg.transformers ?? []
    if (!transformers.some((t) => t && t.path === MERGE_PLUGIN_PATH)) {
      transformers.push({ path: MERGE_PLUGIN_PATH })
    }
    cfg.transformers = transformers

    const providers = cfg.Providers ?? []
    const base = providers.find((p) => p.name === slug)
    if (!base) {
      this.writeConfig(cfg)
      return route // user must add the model first; nothing to clone
    }
    const delegateName = `${slug}${DELEGATE_PROVIDER_SUFFIX}`
    const sibling: CcrProvider = {
      ...base,
      name: delegateName,
      models: [model],
      transformer: { use: [COMPAT_TRANSFORMER] },
    }
    cfg.Providers = providers.filter((p) => p.name !== delegateName).concat(sibling)
    this.writeConfig(cfg)
    return `${delegateName},${model}`
  }

  // Point delegation at a configured model route ("providerSlug,modelId"), installing
  // the compatibility provider + transformer and writing the worker script.
  async setDelegation(route: string): Promise<RouterDelegationStatus> {
    fs.mkdirSync(QC_DIR, { recursive: true })
    const effective = this.ensureDelegateProvider(route.trim())
    fs.writeFileSync(DELEGATION_ROUTE_FILE, effective, { encoding: 'utf8' })
    this.writeDelegateScript()
    logger.info('router', 'Set delegation model', `${route} -> ${effective}`)
    return this.delegationStatus()
  }

  clearDelegation(): void {
    try {
      fs.rmSync(DELEGATION_ROUTE_FILE)
    } catch {
      /* already absent */
    }
    logger.info('router', 'Cleared delegation model')
  }

  async delegationStatus(): Promise<RouterDelegationStatus> {
    let route = ''
    try {
      route = fs.readFileSync(DELEGATION_ROUTE_FILE, 'utf8').trim()
    } catch {
      /* not configured yet */
    }
    // The file stores the internal "<slug>-delegate,model" route; report the
    // user-facing "<slug>,model" so the Settings picker matches the chosen model.
    const uiRoute = route.replace(`${DELEGATE_PROVIDER_SUFFIX},`, ',')
    const onPath = await this.commandOnPath(DELEGATE_COMMAND)
    return {
      command: DELEGATE_COMMAND,
      scriptPath: DELEGATE_SCRIPT,
      scriptExists: fs.existsSync(DELEGATE_SCRIPT),
      binDir: DELEGATE_BIN_DIR,
      onPath,
      route: uiRoute,
      logPath: DELEGATION_LOG,
      feedCommand: DELEGATION_FEED_COMMAND,
    }
  }
}
